[package]
name = "conrods-game-of-life"
version = "0.1.0"
authors = ["pfried <philipsfried@gmail.com>"]

[dependencies]
conrod = "*"
piston_window = "*"
piston2d-opengl_graphics = "*"
pistoncore-glutin_window = "*"
piston = "*"
pistoncore-input = "*"


